### ISSUE TITLE
why not contribute to crowdin's translations?

### ISSUE THREAD

**Issue by bnchdrff** [mageplaza/magento-2-spanish-language-pack#1]
hi, i'm not super familiar with the magento 2 dev ecosystem, so i'm confused why your team has created what seems to be a fork of the crowdin translations -- for example, this spanish language pack is pretty similar to https://github.com/Magento2Translations/language_es_es but with a few new strings (including many ones left as english??!).

why not collaborate on the crowdin project?

**Comment by imsamthomas** [comment]
Hi @bnchdrff ,

This project helps Magento users install language package easier from Crowdin.
All contributions redirect to Magento Crowdin, you can see it in description.
