### ISSUE TITLE
github_contributions.csv

### ISSUE THREAD

**Issue by vandersonramos** [mageplaza/magento-2-spanish-language-pack#16]
Why does this file have language-related content? This should be in es_ES.csv.

**Comment by bfontaine** [comment]
It’s explained here: https://github.com/mageplaza/magento-2-spanish-language-pack/blob/master/HOW-TO-CONTRIBUTE.md#step-2-update-github_contributionscsv
They separate `es_ES.csv` (the original file from the Magento team) from the one containing their own translations, and later merge both.
