### ISSUE TITLE
Replace the German word "Zugriffsrechte" with "Recursos"

### ISSUE THREAD

**Issue by dportier** [mageplaza/magento-2-spanish-language-pack#5]
This line in "es_ES.csv" , contains a German word: "Resources,Zugriffsrechte,module,Magento_Integration"

"Zugriffsrechte" can be replaced with "Recursos": "Resources,Recursos,module,Magento_Integration"

File: https://raw.githubusercontent.com/mageplaza/magento-2-spanish-language-pack/master/es_ES.csv

**Comment by zebeel** [comment]
Thanks for your report. I will update this translation.
